# Generated by Django 4.0.6 on 2022-07-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_old_price_product_sale_time_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='more_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
