from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(
        max_length=50, unique=True, help_text="slug must be unique, it is autogenerated"
    )
    description = models.TextField()
    image = models.ImageField(upload_to="categories/%Y/%m/%d", blank=True)
    is_active = models.BooleanField(default=True)
    meta_keyword = models.CharField(
        "Meta Keywords",
        max_length=255,
        help_text="comma-delimited set of SEO keywords for meta tag",
    )
    icon = models.CharField(max_length=20, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "categories"
        ordering = ["name"]
        verbose_name = "category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("product:product_list_by_category", args=[self.slug])
